spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: customer_db
    password: customer_db
    initialization-mode: always
  sql.init.mode: always
system:
  test: default
