version: '3.3'
services:
  registryms:
    #depends_on:
      #- zipkin
    image: mydarkworld/registryms:latest
    container_name: registryms
    restart: on-failure
    environment:
      - server.port=8761
      - spring.application.name=registryms
      #- spring.zipkin.baseUrl=http://localhost:9411/
    network_mode: host
    
  configms:
    depends_on:
      - registryms
      #- zipkin
    image: mydarkworld/configms:latest
    container_name: configms
    restart: on-failure
    environment:
      - server.port=8888
      - spring.application.name=configms
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
      - spring.zipkin.baseUrl=http://localhost:9411/
    network_mode: host  
    
  customerms:
    depends_on:
      - customer_db
      - registryms
    #  - gatewayms
      - configms
      - zipkin
    image: mydarkworld/customerms:latest
    container_name: customerms
    restart: on-failure
    environment:
      - server.port=8000
      - spring.application.name=customerms
      - spring.config.import=configserver:http://localhost:8888
      - spring.datasource.url=jdbc:mysql://localhost:3306/customer_db
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
      - spring.zipkin.baseUrl=http://localhost:9411/
    network_mode: host
    
  customer_db:
    image: mysql:8.0.36
    restart: always
    container_name: customer_db
    environment:
      MYSQL_DATABASE: 'customer_db'
      MYSQL_USER: 'customer_db'
      MYSQL_PASSWORD: 'customer_db'
      MYSQL_ROOT_PASSWORD: 'customer_db'
      MYSQL_TCP_PORT: 3306
    volumes:
      - /home/shahin/Work/reservation-system-project/customer-db-data:/var/lib/mysql
    network_mode: host
    
  notificationms:
    depends_on:
      - registryms
    #  - gatewayms
      - configms
      - zipkin
    image: mydarkworld/notificationms:latest
    container_name: notificationms
    restart: on-failure
    environment:
      - server.port=5000
      - spring.application.name=notificationms
      - spring.config.import=configserver:http://localhost:8888
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
      - spring.zipkin.baseUrl=http://localhost:9411/
    network_mode: host
    
  paymentms:
    depends_on:
      - payment_db
      - registryms
    #  - gatewayms
      - configms
      - zipkin
    image: mydarkworld/paymentms:latest
    container_name: paymentms
    restart: on-failure
    environment:
      - server.port=7000
      - spring.application.name=paymentms
      - spring.config.import=configserver:http://localhost:8888
      - spring.datasource.url=jdbc:mysql://localhost:3307/payment_db
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
      - spring.zipkin.baseUrl=http://localhost:9411/
    network_mode: host
    
  payment_db:
    image: mysql:8.0.36
    restart: always
    container_name: payment_db
    environment:
      MYSQL_DATABASE: 'payment_db'
      MYSQL_USER: 'payment_db'
      MYSQL_PASSWORD: 'payment_db'
      MYSQL_ROOT_PASSWORD: 'payment_db'
      MYSQL_TCP_PORT: 3307
    volumes:
      - /home/shahin/Work/reservation-system-project/payment-db-data:/var/lib/mysql
    network_mode: host
    
  hotelmanagementms:
    depends_on:
      - hotelmanagement_db
      - registryms
    #  - gatewayms
      - configms
      - zipkin
    image: mydarkworld/paymentms:latest
    container_name: hotelmanagementms
    restart: on-failure
    environment:
      - server.port=7000
      - spring.application.name=hotelmanagementms
      - spring.config.import=configserver:http://localhost:8888
      - spring.datasource.url=jdbc:mysql://localhost:3309/hotelmanagement_db
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
      - spring.zipkin.baseUrl=http://localhost:9411/
    network_mode: host
    
  hotelmanagement_db:
    image: mysql:8.0.36
    restart: always
    container_name: hotelmanagement_db
    environment:
      MYSQL_DATABASE: 'hotelmanagement_db'
      MYSQL_USER: 'hotelmanagement_db'
      MYSQL_PASSWORD: 'hotelmanagement_db'
      MYSQL_ROOT_PASSWORD: 'hotelmanagement_db'
      MYSQL_TCP_PORT: 3309
    volumes:
      - /home/shahin/Work/reservation-system-project/hotelmanagement-db-data:/var/lib/mysql
    network_mode: host
    
  reservationms:
    depends_on:
      - reservation_db
      - registryms
    #  - gatewayms
      - configms
      - zipkin
    image: mydarkworld/reservationms:latest
    container_name: reservationms
    restart: on-failure
    environment:
      - server.port=9000
      - spring.application.name=reservationms
      - spring.config.import=configserver:http://localhost:8888
      - spring.datasource.url=jdbc:mysql://localhost:3308/reservation_db
      - eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
      - spring.zipkin.baseUrl=http://localhost:9411/
    network_mode: host
  
  reservation_db:
    image: mysql:8.0.36
    restart: always
    container_name: reservation_db
    environment:
      MYSQL_DATABASE: 'reservation_db'
      MYSQL_USER: 'reservation_db'
      MYSQL_PASSWORD: 'reservation_db'
      MYSQL_ROOT_PASSWORD: 'reservation_db'
      MYSQL_TCP_PORT: 3308
    volumes:
      - /home/shahin/Work/reservation-system-project/reservation-db-data:/var/lib/mysql
    network_mode: host
    
  auth_db:
    image: mysql:8.0.36
    restart: always
    container_name: auth_db
    environment:
      MYSQL_DATABASE: 'auth_db'
      MYSQL_USER: 'auth_db'
      MYSQL_PASSWORD: 'Shahin@12345'
      MYSQL_ROOT_PASSWORD: 'Shahin@12345'
      MYSQL_TCP_PORT: 3310
    volumes:
      - /home/shahin/Work/reservation-system-project/auth-db-data:/var/lib/mysql
    network_mode: host
    
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - server.port=9411
    network_mode: host
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      - server.port=9090
    network_mode: host
    volumes:
      - /home/shahin/Work/reservation-system-project/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
