server:
  port: 2000
spring:
  application:
    name: hotelmanagementms
  datasource:
    url: jdbc:mysql://localhost:3306/hotelmanagement_db
    username: hotelmanagement_db
    password: hotelmanagement_db
    initialization-mode: always
  sql.init.mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties.hibernate.format_sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      getCustomer:
        failureRateThreshold: 50
      completePayment:
        failureRateThreshold: 50
      completeReservation:
        failureRateThreshold: 50
      getReservation:
        failureRateThreshold: 50
      updateReservation:
        failureRateThreshold: 50
  retry:
    instances:
      cancelPayment:
        maxAttempts: 5
        waitDuration: 1000
      getPayment:
        maxAttempts: 5
        waitDuration: 1000

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus","health","refresh"]
  tracing:
    sampling:
      probability: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html

system:
  service:
    customerServiceName: customerms
    reservationServiceName: reservationms
    paymentServiceName: paymentms
