scrape_configs:
  - job_name: 'reservation-system-customerms'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8000']
        labels:
          application: 'customerms'
