server:
  port: 9000
spring:
  application:
    name: reservationms
  datasource:
    url: jdbc:mysql://localhost:3306/reservation_db
    username: reservation_db
    password: reservation_db
    initialization-mode: always
  sql.init.mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties.hibernate.format_sql: false
  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: notification-group
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: ["prometheus","health","refresh"]

springdoc:
  swagger-ui:
    path: /swagger-ui.html

system:
  notificationTopic: notification_topic
